################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
/Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
/Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
/Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c \
/Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c \
/Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c \
/Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c 

OBJS += \
./Middlewares/USB_Device_Library/usbd_core.o \
./Middlewares/USB_Device_Library/usbd_ctlreq.o \
./Middlewares/USB_Device_Library/usbd_ioreq.o \
./Middlewares/USB_Device_Library/usbd_msc.o \
./Middlewares/USB_Device_Library/usbd_msc_bot.o \
./Middlewares/USB_Device_Library/usbd_msc_data.o \
./Middlewares/USB_Device_Library/usbd_msc_scsi.o 

C_DEPS += \
./Middlewares/USB_Device_Library/usbd_core.d \
./Middlewares/USB_Device_Library/usbd_ctlreq.d \
./Middlewares/USB_Device_Library/usbd_ioreq.d \
./Middlewares/USB_Device_Library/usbd_msc.d \
./Middlewares/USB_Device_Library/usbd_msc_bot.d \
./Middlewares/USB_Device_Library/usbd_msc_data.d \
./Middlewares/USB_Device_Library/usbd_msc_scsi.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/USB_Device_Library/usbd_core.o: /Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c Middlewares/USB_Device_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx '-D__packed="__attribute__((__packed__))"' '-D__weak=__attribute__((weak))' -DUSE_HAL_DRIVER -DDEBUG -c -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/device/st/stm32f4xx/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/stm32f4xx_hal_driver/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Common" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Device" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/class/msc/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USB_Device_Library/usbd_core.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USB_Device_Library/usbd_ctlreq.o: /Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c Middlewares/USB_Device_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx '-D__packed="__attribute__((__packed__))"' '-D__weak=__attribute__((weak))' -DUSE_HAL_DRIVER -DDEBUG -c -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/device/st/stm32f4xx/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/stm32f4xx_hal_driver/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Common" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Device" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/class/msc/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USB_Device_Library/usbd_ctlreq.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USB_Device_Library/usbd_ioreq.o: /Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c Middlewares/USB_Device_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx '-D__packed="__attribute__((__packed__))"' '-D__weak=__attribute__((weak))' -DUSE_HAL_DRIVER -DDEBUG -c -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/device/st/stm32f4xx/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/stm32f4xx_hal_driver/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Common" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Device" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/class/msc/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USB_Device_Library/usbd_ioreq.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USB_Device_Library/usbd_msc.o: /Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c Middlewares/USB_Device_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx '-D__packed="__attribute__((__packed__))"' '-D__weak=__attribute__((weak))' -DUSE_HAL_DRIVER -DDEBUG -c -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/device/st/stm32f4xx/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/stm32f4xx_hal_driver/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Common" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Device" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/class/msc/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USB_Device_Library/usbd_msc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USB_Device_Library/usbd_msc_bot.o: /Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c Middlewares/USB_Device_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx '-D__packed="__attribute__((__packed__))"' '-D__weak=__attribute__((weak))' -DUSE_HAL_DRIVER -DDEBUG -c -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/device/st/stm32f4xx/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/stm32f4xx_hal_driver/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Common" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Device" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/class/msc/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USB_Device_Library/usbd_msc_bot.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USB_Device_Library/usbd_msc_data.o: /Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c Middlewares/USB_Device_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx '-D__packed="__attribute__((__packed__))"' '-D__weak=__attribute__((weak))' -DUSE_HAL_DRIVER -DDEBUG -c -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/device/st/stm32f4xx/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/stm32f4xx_hal_driver/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Common" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Device" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/class/msc/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USB_Device_Library/usbd_msc_data.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Middlewares/USB_Device_Library/usbd_msc_scsi.o: /Users/nico/Desktop/SEcube\ firmware\ 2/environment/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c Middlewares/USB_Device_Library/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx '-D__packed="__attribute__((__packed__))"' '-D__weak=__attribute__((weak))' -DUSE_HAL_DRIVER -DDEBUG -c -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/cmsis/device/st/stm32f4xx/Include" -I"/Users/nico/Desktop/SEcube firmware 2/environment/drivers/stm32f4xx_hal_driver/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Common" -I"/Users/nico/Desktop/SEcube firmware 2/environment/secube/src/Device" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/class/msc/Inc" -I"/Users/nico/Desktop/SEcube firmware 2/environment/middlewares/st/stm32_usb_device_library/core/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/USB_Device_Library/usbd_msc_scsi.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

